apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: ghcr.io/ghcr.io/filipevrevez/go-kafka-consumer:v1.2.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: kafkaURL
              value: "kafka-headless:9092"
            - name: kafkaTopic
              value: "test-topic"
            - name: kafkaGroup
              value: "test-group"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: ghcr.io/ghcr.io/filipevrevez/go-kafka-consumer-producer:v.1.2.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: kafkaURL
              value: "kafka-headless:9092"
            - name: topic
              value: "test-topic"
